// Auto-generated by deploy.js — DO NOT EDIT
// Every deploy gets a unique timestamp → impossible to cache stale data
const HR_BUILD_VERSION = "2026-06-19T14-34-31Z";
const HR_BUILD_TIME = "2026-06-19 14:34:31 UTC";
