// Auto-generated by deploy.js — DO NOT EDIT
// Every deploy gets a unique timestamp → impossible to cache stale data
const HR_BUILD_VERSION = "2026-06-19T20-04-56Z";
const HR_BUILD_TIME = "2026-06-19 20:04:56 UTC";
