// Auto-generated by deploy.js — DO NOT EDIT
// Every deploy gets a unique timestamp → impossible to cache stale data
const HR_BUILD_VERSION = "2026-06-19T13-25-21Z";
const HR_BUILD_TIME = "2026-06-19 13:25:21 UTC";
