const artistData = [
    {
        "name": "Doc Gruesome",
        "spotify": "https://open.spotify.com/artist/7lqUnVMVBec4l7YhVbYl8K",
        "instagram": "https://www.instagram.com/doc_gruesome/",
        "website": "https://www.cerberusclique.com/",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/docgruesome.jpg",
        "description": "Doc Gruesome (Nick Lorton) is a Reno-based emcee, graphic artist, and creative force carving a lane where hardcore rap collides with nu-metal, goth rock, and punk chaos. A founding member of Illtrix and key architect of the Cerberus Clique, he has spent over a decade building one of the underground's most distinctive and uncompromising identities. His sound draws from a wide range of influences including Slipknot, Deftones, Sisters of Mercy, Depeche Mode, Tech N9ne, and NWA, blending rapid-fire lyricism with haunting cinematic production to create something that defies easy categorization. Raw, emotionally unflinching, and deeply personal, his music channels real pain into visceral art, tackling mental health, addiction, survival, and resilience with a honesty that resonates far beyond the underground. As a visual artist, Doc Gruesome extends his world beyond the mic through custom graphic work, high-end merchandise, and handcrafted replica masks, creating a complete aesthetic universe that is equal parts grimy and meticulously crafted. His storefront, Cerberus Click, serves as the hub for his ever-expanding creative output.",
        "releases": [
            "5aq0A8TGeGQUWg0NvOYWv0",
            "1JUOl4ys0bO4zonRkOqwX2",
            "3L1oJZXHtEDU45iQ9yp1Ul",
            "3cubaKd12QpQxk1F3nlKJ2",
            "1jcjsSVw3il2vH4NDZXm2t",
            "2blba2gfdloaSkaA1fWCBK",
            "5PSluJmJRAHP4P4KXMpNx3",
            "50Ryi1a1WnLJRRVKQF4RR1",
            "5dFxzhmCNhBK2cLn2YXXMn",
            "1PvIrEDstIHNVC3HIUCiLK",
            "14mWn6fvNm7URamrIMwrW5",
            "4v5GAqh9ml8ZpmagbWFRyf",
            "66T1grK4kb4BcI96K50iJX",
            "0uFKhntrwCcIH8x8rYeyKh",
            "6353chwQXvQHc4ehqxNgM6",
            "4GHKbYZnqsGLx7V8qtJ3V6",
            "3iLyNh8YIKEPCWSKRgLMbC",
            "6OHXnBFxvn4fMApZ1jcvJo",
            "0Td4zAiqZpR4Xwyogxw9nr",
            "0ktNkeqYXP4eZ2FReAMYnm",
            "1chK1WAaXirggFmUqXKb6W",
            "6TLIx8cQJuHQH1uRUglf5Y",
            "7IqyPDbLepAN3Td9GzSRtL",
            "34FgR2kzRKEGYQQ7QrbDB0",
            "1WGK4p9N4RMPaDMJstYKVQ",
            "1JUkrBhgJiVFmKltxXuGba",
            "2QMQpFlg1LfDRmbgvd4rpo",
            "4aHnWG1UG2sSBD2kZt4eQx",
            "3Lzsb5rWPqkAdHDBVsK4rL",
            "11txnt9CD3r9GFqG1ZNdXp",
            "0MPuvlyrftIcvtS24ZSssF",
            "0lGpGvDsLiuzfVYsD9E7ao",
            "4sKOyUoTzfTdYKlQJMfMdL",
            "3b9UDyxhYHJLrpI8ZbCymp",
            "2oX90D1WCxNChBbC0V9YRr",
            "4VCfjBnaFwq3RVt0xVuWZA",
            "6JAQX1ahy2oMOovPWZOZP8",
            "2x5jz5SzkVcX3MbUwKJl4j",
            "1gObCauVStp7COocjaULjd",
            "5QWEjVzLAt4AwnyG8QIXIk",
            "0QYVyQ3O5ktx3rdpwN0xmx",
            "2aD1KWYSKC4M9xPr44Miy6",
            "0tE8tltsZGqI8rLgFa8SyO",
            "7EnricwDZlUWQn5lY7Fjcg",
            "2jC81nkw0jEfuTOMdLX5Rp",
            "0Os5BGfi17Vs8mE2kFKEvy"
        ]
    },
    {
        "name": "Something Outta Nothing",
        "spotify": "https://open.spotify.com/artist/1ZtPp25giGKyQUeKlHTGnR",
        "instagram": "https://www.instagram.com/kingofdarkenergy/",
        "website": "https://longliveevil.bigcartel.com/",
        "img": "https://i.scdn.co/image/ab6761610000e5eb2b3c079f402c3e2e5b86b325",
        "description": "S.O.N (Something Outta Nothing) is a horrorcore rapper out of Sharon, PA who built his name from the ground up under the alias Scrub King before rebranding with a sound that goes darker and deeper. Rooted in classic boom-bap production, S.O.N layers gritty, confrontational lyricism with themes of ritualistic black magic and occult energy, a combination that's earned him a loyal following in the underground horrorcore community. His hustle goes back to at least 2011, when he dropped his Scrub King Mixtape, followed by D.U.I. (Dying Under the Influence) and a collab project in 2012. After years grinding in the underground, he returned in 2021 with Grant Us Eyes as S.O.N, and dropped The Bastard Son in 2025. In June 2023, he was officially signed to Long Live Evil (LLE) at Camp Xul 3, cementing his place in one of horrorcore's most active rosters. S.O.N has shared stages with major names across the horrorcore scene and built a reputation through years of collaboration and touring in the underground. Something outta nothing, indeed.",
        "releases": [
            "5gQKJ9Pp5JZwTVTJn0BH5e",
            "6IOEnuQXPIEvsQEbakPDrg",
            "0JQg7eikxPPHrBwDnYtJjw",
            "7eZEzjnLCcjAv7RnvLLrGv",
            "5TVl98AqB1soKNB9RLsR4i",
            "1I2HA3tI9TqLS7ZUxd5plQ"
        ]
    },
    {
        "name": "Grim Salvo",
        "spotify": "https://open.spotify.com/artist/5UogEGDRYo5Q9bRIMRjuEC",
        "instagram": "https://www.instagram.com/grimsalvo/",
        "website": "https://grimsalvo.com/",
        "img": "https://i2o.scdn.co/image/ab67618600001667ba6e30a727e5d3f261aa5f13",
        "description": "Grim Salvo is a dark trap and experimental duo out of Portland, OR, made up of childhood friends SLEUTH and MOSSBACK. The two met growing up in Portland and eventually built a sound together that blends trap metal, grunge, and horror-infused aesthetics into something raw and distinctly their own. Both members are also part of the three-man production team Â³Â³marrow alongside audio engineer Jeremy Klein, giving Grim Salvo a tightly unified sound from the ground up. The name, as the duo has put it, was something they randomly made up but felt like it perfectly captured their purpose. Their 2022 project Mildred and the 2024 release VOIDSTâ˜…R have cemented them as one of the more compelling acts pushing the boundaries of the horrorcore and dark trap underground, with a growing fanbase that continues to expand through active touring across the US and Europe.",
        "releases": [
            "5iSsvkysEm4sjAWzLZvYBq",
            "3jae2GNwWp7557szjtj0ke",
            "5OBtYdpWmoyEVWPllhrVKj",
            "7ksPxrBTs9H35LoGia5zq3",
            "6D8mIYnzouehNA0S0E3qvB",
            "2KwCTJylW9PWCj1u6mPK1n",
            "48rUMdvw5W4u5NiHyq4owg",
            "2RhHXm0yH8GzrgWftESz4Z",
            "1RGXboLcIwKf1aYwchqZNk",
            "6shFiJsED3fVGbiOULhtKz",
            "0y8IEMDd1kM48mkvsBBj3U",
            "6RDAulwV1Iq52DhOnjIoFp",
            "2I7HLr0sUFrdDOalAlWE7L",
            "5eYGi5ty7PfqXZ9JzpdIvC",
            "5sU6Ljpr6EwKXoThSkh2Ye",
            "1TWl96DZQW2A8ii4n5Esai",
            "0GwyHBG0Urb5I5058pN1Gj",
            "3TfJe0gRUYcH8nECv4RJnt",
            "1tN4GEEdKH7cwAg2t5LqWh",
            "25317HDefIRr0bbooOLUiu",
            "0ZbethZRzM03ZxAiAR8EPJ",
            "47IEjkWlOdMr4OnA013haT",
            "2XkoHJNgp6s2jof0HxlP7q",
            "1HeyidK2eiHqD0b1lULyna"
        ]
    },
    {
        "name": "GODHANDUSA",
        "spotify": "https://open.spotify.com/artist/52XZBIfTRn9iyM7QLf6DmX",
        "instagram": "https://www.instagram.com/godhandusa/",
        "website": "https://www.godhandusa.com/",
        "img": "https://i2o.scdn.co/image/ab67618600001667e436d26d0fecccc63b6c3963",
        "description": "GODHANDUSA is an aggressive underground duo out of California, made up of Gonda and Mongo, two aliases adopted specifically for this project. Part of the Spider Gang collective, the duo channel a sound rooted in Memphis rap and cloud rap, filtered through a distinctive 8-bit vocal effect that gives their music an immediately recognizable, almost lo-fi video game quality. Since launching in 2024 with GODHAND VOLUME 0 and their debut proper GODHAND VOLUME 1, they have moved fast, dropping GODHAND VOLUME 2 and the mixtape IGNORANCE IS BLISS in 2025, followed by GODHAND VOLUME 3 in 2026. The project has a loose, high-energy feel, equal parts fun and unhinged, with the duo leaning into the chaos rather than away from it.",
        "releases": [
            "0XPZj7cckuT6tQ0BQeSfYI",
            "2PKM1ic0L8LyhrkwMa4Tom",
            "0AxuZuHTIPO0tcJ3xjnWjl",
            "0Wvhhn3mHQaBeS9a3M77dX",
            "1sAr7ylbTfTyPnNT17ZwZI",
            "7CW4FfVZu66BPrBrq5buza",
            "3A47GgDbKSUIASrbiV6FHA",
            "0E1v0BdcnaBOWGCT1gQU7f",
            "3Z6Nlc4IpIGa7jquBF5m3f",
            "2gkG4LAhhlQdVQ6n0cyLma",
            "3NcaTHIkFuzZaBFguBlNh9",
            "7Lw3b9lkNV9SuLGOfHAMxV",
            "2dZhZqPfpzXhh2PCisb0se",
            "3dpBKEUBqttAxShbmGzI0c",
            "1NIw7Y24vIiYnzi0j3TVgu",
            "20cDKHe9D7yJ5GhjPAKaEw",
            "547cjoSfMIjnEXEDPG9I2q",
            "4YzFxhWtP97GIlqKq096zo",
            "2i2obyzsrt5UiZcOnU90EL",
            "7qK9WbHN6cvIRKrygKqANQ",
            "0tLnUCRwWhxcAerR5Wyna5",
            "1jyo01HuaIQo2fMfWBLg1R",
            "4s8YvRodJh6bGtx5qHSd7R",
            "0bFT0tQeFZC73j5OaDOLKD",
            "7dGSEgVLuD2NyDl0HvB4Lc",
            "2QaRddiOaOYjacDvuZ6j84",
            "71z8WjcL5la9jxieELSUhb",
            "0yoRCHrtLXPzlWAQ9qlgGp",
            "3CKklPQEUgJeP8ijfRfEDO",
            "1mU034zumR5Otnp8COb32Z",
            "56R8upRk37Ae96bUJkMTCd",
            "55UzcH5VZa4go3aoYycRCj",
            "4BZJoeAa2XhpAYcIIv9JcZ",
            "3iiaoDbegf42GdVGpl7HXc",
            "3hURqHm84t7XF1QyfNDJSb",
            "4iI9aWIms4WrinfD9PVXWS",
            "1l3CAWGdNgUKAsIbjZv6eJ",
            "3va1MM5woCDa37w65LkPlN",
            "1rn9L3Wj1Kn5iF2yV4XjhF",
            "09XqiaEbU6AtTNO7FVoG0u",
            "01jPGExQNGUrCmPyAVskFi",
            "0ULwwzPKvLx6wfskASI75k",
            "6n9ogm11pwvYAvqcqgUO4l",
            "19XTZVP9PSnL0TXpMIVA7o",
            "53FcxHisVbhWOni4jkP3Ax",
            "0eVpnYFAllG1E9lWWUdJMZ",
            "1ztgi4s0tAk2kqeaPAUDu3",
            "1qIEzQVayQMOBN0vRE5tkr",
            "26hQzsmzKvs3HyItJwdEvb"
        ]
    },
    {
        "name": "Kill Dyll",
        "spotify": "https://open.spotify.com/artist/1r5YzslA0QwyIZISgHJrU7",
        "instagram": "https://www.instagram.com/killxdyll/",
        "img": "https://i.scdn.co/image/ab6761610000e5ebb8700b15b310e2f1f0fdae1f",
        "description": "Kill Dyll is a Denver-based trap metal artist, producer, and visual creator who has built one of the more distinctive identities in the underground scene. Starting out as a drummer, he eventually began producing his own beats, rapping over them, and shaping a persona he describes as an artistic interpretation of ego in America. The result is a sound rooted in heavy bass, distorted vocals, and confrontational energy that pulls from hip-hop, metal, rock, and industrial. Everything about the project is self-contained. He produces his own music, directs his own videos, and makes his own handmade masks, the horror-themed face coverings that have become his calling card. That contrast between the unsettling visuals and his more reserved off-stage personality is a big part of what resonates with his fanbase. His discography moved fast once things clicked. sixty se7en and JFK in 2022, dont touch me. in 2023, and a run of releases in 2024 including Antagonist, EMBRACE THE CHAOS VOL.1, and the Warner Records-backed mixtape BRAINDEAD. Most recently he dropped ACT HUMAN, not god in 2025. With a rapidly growing fanbase and major label backing already in the picture, Kill Dyll is one of the scene's fastest rising names.",
        "releases": [
            "2L5UXxpRR0au82NbHDtxuT",
            "4xACBGqzOhJ8A0YJzqAvEn",
            "5ofCVTeAyVGwPj6z9m1P7X",
            "2i08mMiFf51QxvDTJlhq2J",
            "7MEHRApivqwtI0cHij0nW8",
            "6T0OU2OF3jcMKs5pkUjsgy",
            "7z4bOVyff5FTaDeIIjPXXs",
            "4XQCQ0pqXOY7Yf43HsodK9",
            "3QAvdHz2tHhudtH6gmywd4",
            "4JCeiarWdfm1WV86ZsNa1b",
            "0mtCMvqtnCTM2cYhVVtKUn",
            "433a3JCXuGFttadC5LAQmF",
            "3xicMBqt5AQ3ywWdi7ahfA",
            "3C4ldrZddMtPQRUFKS43Zk",
            "6TwVVL61TxuFiQGDFMBXql",
            "5mkkXvKZxkiwJNlWkNaksW",
            "40BLH68NAkViz0aeemrKFV",
            "1vqmwhaB1zeMb0WlexCbUK",
            "1LZL49eCQaK33GI1JOVNfD",
            "2Ut99Lzl7p2JWWE7ACN9vg",
            "3VPdcSoaLisWUhljemXBe6",
            "3oPCmFvO7oTZz1tNHEdy6I",
            "4qtGOyxc4MfopoH9b8xuYd",
            "21RBXYEl4j5anWHKQjvMvf",
            "3H8w7JNjMXAeOpuEUWck0G",
            "2YIXE4N8I8zZ5y0IXT4q2v",
            "7be4xm8QKyrU69PnkD3XTF",
            "01S0x2Qp6CODlQko0MPo0y",
            "4OqEKSK9aSeTvXJFBC8Jbl",
            "3G4Pv4Gi9uYaUjh1x0vXia",
            "4uQJLwPsc62jnR5U2MOOsb",
            "6nQyYMaYNecW1Z509oxuwz",
            "0LGT47XCH61BWvIOGJNNr6",
            "73Bd2a8RysDAnvrL7OVUpN",
            "75vPJKIGknbHtlbePsRUgy",
            "0UPDi5RpZMSflqSBnxldOh",
            "2UHyycPzeP2HPvh32dcMHT",
            "2NtXF40V1KiF9v7v42gek1",
            "4noSgxGI4MVIQEKYSOjN5F",
            "45JlvYTmw091d5NtnJMOAq",
            "6vhncD53WbI2mjP3coH7Jo",
            "6R6YG6GzOrBGf8PB1OGXlY",
            "3SnR5AxkMmqsUz7pILA3HD",
            "1jjnLhhCwqr0mUzsQUlSsT",
            "1ece0jN4ViEKMpqcl4ObjO",
            "5YATkYRxFToKLTwBMALL5X",
            "6A8cGDoUcSHqnOOttflLFt",
            "0ZqlNg55XUnkbqYAA1FpLu",
            "3lMDnVJaKnjP0GekAa8tS4",
            "5wGr6XiuA1v4d65FUzrUX0",
            "6ObpmdMIeOz98Ha2zfiBZR",
            "77SqvVMbpuK2smFEA0Q3GP",
            "0i5pRuu74MuyPrIjbsW6MI",
            "1nglfqOPCbFAJBYQCMjJvB",
            "1a5NiGJynAPGKyGU1cYqtE",
            "1Rt6nfCZCW7DBHJbQErFZW",
            "2OYkWtc3PfBVi7u0u267fF",
            "2rVweRPrGG5dugtZKHcD0U",
            "1qa5QExQKR4mKfqaoSh5Ac",
            "2sQH8kavnWueFKhcBc2wGr",
            "1tYsU3bWcIwiCP159az1ip",
            "2ceKtUIRPkQU7u8MCgs8cP",
            "1KjXGmwRCkzdFCtyvyX5hm",
            "7sdjC5ysJhNOEkOaoh6hHy",
            "5hvL4lijECGPrZLmOLuyYh",
            "0A2F5SGHMxAaoJNz82r4o2",
            "5U2tJZGSGeShKkh3ifnuqu",
            "6XMNiPYdh3X5oNYSR0lOZ2",
            "2oz6q9Kj0tB5nMEZkrQdOV",
            "5ZlXMimK427p7AorUHqwh1",
            "5csDfvRZxbelCk8T2tJnu9",
            "5LISdolYhKiSeh3FmyJGoj",
            "1LZ4q2eIrKjzHkPE019FWw",
            "4dlCZi6Nj17NZy4v8AzpiF"
        ]
    },
    {
        "name": "LuLuYam",
        "spotify": "https://open.spotify.com/artist/4TAg5ckpTlxXLPTJW4eDMo",
        "instagram": "https://www.instagram.com/luluyammusic/",
        "website": "https://www.luluyam.com/",
        "img": "https://i2o.scdn.co/image/ab67618600001667b9a5723ab39fecfdd06f281c",
        "description": "LuLuYam is a Florida-based rapper, producer, and visual artist carving out her own lane with a self-coined genre she calls Nightmare Pop. Blending hyperpop, hip-hop, and dark experimental sound design, her music is deeply personal, tackling mental illness, trauma, and the fractured inner self through a horror-tinged lens that is entirely her own. At the center of her work is Lucifer Lucifer, an ambitious multimedia project that ties her music to an original story and cast of characters set in a nightmare realm called the Nightmare. What began as a comic series has since evolved into a planned visual novel format, with LuLuYam building out a fully fleshed lore-driven universe alongside her discography. The project is entirely self-made, from the music and production to the artwork and character design. Managed by zombAe and fully independent, LuLuYam has built a dedicated fanbase drawn to the depth and cohesion of her creative world. One of the underground's most genuinely original voices.",
        "releases": [
            "0i2YrxbwlJb3eUzvSVqSXI",
            "4piPwqBGxq8hlWONUMMrf4",
            "2KzRFjVkEQwvvyWOqBEEkJ",
            "0ACs6agGjx6xMoGpOTcWxp",
            "1p3et41krclrEPRo004AHN",
            "0wo2bZpG7z27ROlQYPAmlK",
            "0QlEmz0W8mNITbr3guElUM",
            "11qLcN5HgjgAlFUnrUB52h",
            "52BWb269m7R4b4BebgB00p",
            "4LRPCa3wyfSuuFgPxeytRx",
            "7xab77w0mqH4ahD3jlzF1D",
            "53byhoZELZngPlPwbpOyWb",
            "2FjusBhEyTYXc1rbJxwnRM",
            "5a4mIKRec73w5gFAHXnbuH",
            "48WOPGbBqSDsePdqOGi1V0",
            "0pPaKLsaZLn7Pm1HUs17v9",
            "7zs6FxgG82tR3RSbDFltvF",
            "49NXGz55zTSV1fWkuiFTwW",
            "0LRCaA44CyRwCbCpVkK3oY",
            "1xjoYxM29c910GWC7BBAah",
            "6gGBBnCivtdZAKcWVzPgTk",
            "5h2ii0AQ2fSE0Bdz99BXVR",
            "7iAdx6ehqVtLUMaRi0k6TH"
        ]
    },
    {
        "name": "Klokwerk E",
        "spotify": "https://open.spotify.com/artist/1jJ2naBvqDjeQXuHT86Rdo",
        "instagram": "https://www.instagram.com/klokwerke/",
        "website": "https://www.klokshop.net/",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/anubis.jpg",
        "description": "Klokwerk E is a 5th Dimensional Hip Hop duo out of Columbus, Ohio, made up of Billy D and Kyle Kombs, better known together as the Silver Boof Brothers. Their sound is hard to pin down in the best way, blending underground hip-hop with dark, absurdist, and conceptual themes while keeping things deeply human at their core. Kyle Kombs handles production, and his beats have steadily evolved with each release, while Billy D brings the lyrical energy and personality that makes the duo click. What sets them apart is the range they manage to pull off: their catalog can go from grim and heavy to genuinely heartfelt, often within the same project. Since debuting with Will Boof 4 Rent in 2023, they have moved quickly, dropping the full-length The Emerald Tablets, the acclaimed Anubis, and multiple EPs in 2025 including Bukkake Mukbang Extravaganza and Rent a Friend. They have also formed the supergroup Mighty Morphin' Wackness alongside the Super Famous Fun Time Guys. Nobody outwerks the KLOK.",
        "releases": [
            "57juRrWQFS24QXtRNcQN4f",
            "7dsmX0EMNXim5EMwC5BuIB",
            "5PWECdOnou8X3kVbC78iCh",
            "25HM5S9LjuGxuGhVi5a9U9",
            "3VHV4aX2FkesuiNIbd09uQ",
            "6XI8FYFERtmAXJOSlKZfX6",
            "42ReVOGNhQJISgbPZSe5d0",
            "0xcNqQOt0Ub7KKRabwYSGW",
            "1BVV7yNk76lGGHtdTmkcoy",
            "6mS5DsaRRqIcfiha3UESEZ",
            "2VkMZIZ6yampqjU4tV18Fg",
            "7pwMsxN7pi55CWm89zY6hz",
            "0y9Oc6LfW51zzn3tqTefLZ",
            "0RZ4W0ZbgcEEbRFtRIWgsM",
            "4YKAAlMDm5WVwgB16WYwsG",
            "2rJMG4rxaYvXm92unsH3Vv",
            "7GQ1uwTO12HBfePwOlX46C",
            "2Vlh3LzXqOuJoRc6xbsby1",
            "6jdH3mdZTlvzzySCr0Y5eW",
            "527TvChcbg5D6sWiZGIlnJ",
            "6y2ecFplbFDy9tKjSCs3vH",
            "5tpT3WGVBMsPlxTN73UOGK",
            "5NpCvbAYQqca8d8jzDjH2f",
            "79DovyawHDs4doScoAU6e2",
            "7llwDpqVKgcwUe46QsSqOe",
            "3eNvcQMhek1krhgy56Pt6S",
            "1tyTj74itz6IYZ70gtp723",
            "6mQytMCfck0gjhd8iuN8qj",
            "0UmuMsd500eNBtA7QjjvR2",
            "1bUDKRJPrDtVEJsbn0Uxzl",
            "5pNkd5ZnKy5GP9SBnrx77s",
            "25UEuY8a14cXYfozV33yHc",
            "41AKTMQXuhRlfwgw3gsXgf",
            "0vxSUBLaPrAextUEtdbvGY"
        ]
    },
    {
        "name": "Blood of the Beloved",
        "spotify": "https://open.spotify.com/artist/5rvjrOCjjFU5JRCLkUl5pB",
        "instagram": "https://www.instagram.com/blood_of_the_beloved/",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/bloodofthedeloved.jpg",
        "description": "Blood of the Beloved is the collaborative project of Nyte Shade and Skeptik, two seasoned underground artists who bring very different but deeply complementary skills to the table. Nyte Shade brings the hip-hop and horrorcore backbone while Skeptik, a one-man heathen metal act from St. Louis, brings rapid-fire harsh vocals and a wide palette of synth, atmosphere, and metal influence drawn from folk, industrial, and extreme music. Together the duo sit comfortably in the space where dark hip-hop and horror metal collide. Signed to Solunar Records, an independent label and artist collective, Blood of the Beloved debuted with Advocatus Diaboli in 2021, a sprawling 16-track statement that was remastered and reissued in 2024 as Advocatus Diaboli (The Dead Master). Blasphemous in theme, experimental in execution, and relentless in energy, the project represents one of the more genuinely cross-genre entries in the underground horror scene.",
        "releases": [
            "3bOQee5U3riUBMIRC8rvy0",
            "4LrAv3rKELg7vJpBcOAgDi",
            "7HBvZsMl1myghoqVY0xYBI",
            "6uXRVaXBnIe1w1H3XaWxEu",
            "2eCRJJY5jeWPedpps6EoWu",
            "3ri79iOePwwHCeBomVko9u",
            "27PNbaQZ2cege7vZWnVng4",
            "5fijItn7QC7wMYLsQ8sdYr",
            "6X49pMM3NeSFB7JEv9cSTg",
            "4ayvv4RRuJynVQeKe9sLI8",
            "1vuDNzTOugD90VzUVPS5TR",
            "4GY6YUjYB66VDYa3ZADDbR",
            "3DxlL80aTuRIvIaGspzZvS",
            "6RVbq7zPsXT4xE4xas7J6A",
            "1xG7Vm2gFh4zcdHinOGjXW",
            "3rclrKzJdEKeKvliPmJ5d8",
            "70CbGCmXI8f0z1CiN6FlFT",
            "7kZRNI784PcG7fQPosebeN",
            "0vaJbQsRrtsGLJdLGCLNe4",
            "121qbS8gxE055XXVA6HCAF",
            "3vrhXZHpxzGPttH5ppsKa6",
            "3XRFu31WWlw6ccQLzUjfVp",
            "3XYPkAkb3D2wqOjaJfYz1e",
            "0iOSfXcxc91MBucE67itHv",
            "3JM9mSPgx8mXARl6ArwjeI",
            "69O3bm2T26nBvyQV7ImmaV",
            "7iKnVWh4dHHRSnnqCK7C4T",
            "72paWGxAm9RzCkuzyBF1j8",
            "1SRc1YVns1H0cuH3jqNab8",
            "10VTwZasaH0S2Rp2ifieYY",
            "1xQz9LLTwetskKpNMn11Ja",
            "589kLkXaDZ4hbBQEGXLDo5"
        ]
    },
    {
        "name": "KAMAARA",
        "spotify": "https://open.spotify.com/artist/06d6Jun2N1hugnXeN98kQ0",
        "instagram": "https://www.instagram.com/kamaara/",
        "img": "https://i2o.scdn.co/image/ab676186000016673f9c40ab026b61345676404e",
        "description": "Kamaara is a rapper, producer, and artist out of Fort Lauderdale, Florida, now based in North Carolina. His sound is rooted in trap metal and industrial hip-hop, built on dark, heavy beats and an aggressive delivery that has been his signature since his debut in 2017. His solo discography runs from Valley (2017) through Next Time You See Me I'll Be Dead on Your Doorstep || (2018), Cowboy Cutie (2019), and TrenchBoy|| (2020), each project pushing further into experimental and atmospheric territory. Beyond his solo work he is also a member of the collective Haunted House, and has a collab project with Savage Ga$p as well as Circling Terror with Kill Ebola in 2025. He produces much of his own material and has built a reputation as a tireless collaborator in the dark underground rap scene. With active touring across the US and Europe, Kamaara has steadily grown from a regional underground name into a genuinely international presence.",
        "releases": [
            "3of56j2BnYbsNkg1VUpaRy",
            "3lKy1Ddnt6Jov2ALre3Cao",
            "0Vfy5ukBUXEVzArLDIE8Ye",
            "6mfq6WTN6KbkQADZGGPDL5",
            "5SRhjLtuq84q8wLvSazmpS",
            "3P20mv4bbLNQo4fDaw1xBB",
            "0ryBgUnptNCupir6KF0Q6n",
            "6RgO0HKGiXgBhJbkVcm9lT",
            "6xLqhaKRper2MaawxE7Edf",
            "71ldCC4LYRGxMjMW36fQyw",
            "0p6HOkxIjtAoiDpfSbvSHU",
            "4Y5pBfHSb1Ojay1rLxj45C",
            "59OFpC7J5h3OcyXG5NPf9Q",
            "1RGXboLcIwKf1aYwchqZNk",
            "4PXrQD7Bd00EjJnyb6maH8",
            "4HAON7JRIvpZg5qMGqOMN2",
            "2ZSmQMtAl10dAyU1eneFbo",
            "1rxIEvAI88gl1lBDsjvZqZ",
            "25oNU5hHbzv3GAF8UfLZUy",
            "5paHLzewvgX7QCz1LP73MO",
            "6P79MWNcyqDUyXlB6ykiAT",
            "0y8IEMDd1kM48mkvsBBj3U",
            "2BSWt8nsXXqEEFBlkfzqvm",
            "63mm4ZMw3FGmwW1nCtMy09",
            "3YEK8l1byfJUnRCvkywy0q",
            "5UsQ3HlF9ztCzjt2k2OkeO",
            "18dLFncnmkXqgHeUkmXpwF"
        ]
    },
    {
        "name": "Witchouse 40k",
        "spotify": "https://open.spotify.com/artist/7chdPv6Kx0frN0lKfppD2J",
        "instagram": "https://www.instagram.com/witchouse40k/",
        "img": "https://i2o.scdn.co/image/ab67618600001667ba193ab32dfcf3ed59a0be3e",
        "description": "Witchouse 40k is a trap metal and shadow rap artist born and based in Portland, Oregon, whose name was inspired by the Warhammer 40k universe, a fitting reference for someone who builds his sound like a siege. Rooted in his earlier days playing in punk bands and a long obsession with dark underground music, he brings a gritty, atmospheric intensity to everything he makes, layering horror themes over eerie, heavy production with a voice that is immediately recognizable. He debuted in 2018 with Warhammer and has been relentless since, building out a deep catalog that includes KILLRADICAL (2019), 40 Years of Rain, Bad Strains Tape, and Blood Bender Mixtape (all 2020), LEFT FOR DEAD (2023), and his 2025 full-length Ghostlands. Beyond his solo work he is a founding member of the Haunted House collective, founder of Hellhound Militia, and the leader of the SWARM movement, making him one of the more organizationally central figures in the dark underground rap scene on the West Coast.",
        "releases": [
            "2n90ugazhgrJYNwgKCSp5B",
            "5iSsvkysEm4sjAWzLZvYBq",
            "5K3ZioWTtEeVj90pZIye5W",
            "2KwCTJylW9PWCj1u6mPK1n",
            "48rUMdvw5W4u5NiHyq4owg",
            "2RhHXm0yH8GzrgWftESz4Z",
            "2YIXE4N8I8zZ5y0IXT4q2v",
            "7ICcTCaT1S0q7mgQXVWwd0",
            "6sNS7e4Hj0gQapOdWAC7g8",
            "45nzVVJgYMJXfQVXPEYRLu",
            "7tBwhgKcp1DFJ4f0Au0Jdh",
            "2ResyJBYR0ZSBN6WlyUeoR",
            "3B00Yjkqx81gqsV79wYqzZ",
            "3doXPRLa4oDDDxOdrBir5X",
            "7xBKaxKoh1UjuEHbjG2MqM",
            "1eF11iEKjxErQm9jSIbDTL",
            "3FZ08nXmg4K74lhpDj9s1s",
            "4PsteQRrsRlx1wZJJ0DTWP",
            "0YBTrz75JgJZlGgFMIdYAg",
            "6nG7XjSnNuNcZDlkjgag9T",
            "67ANrS3XLSDDqVPzwaJZHk",
            "1dW8xore3BEE2Og1sK5APV",
            "2Y4cqH1wKDTz5MhQNQMRZZ",
            "128fgsPnKu0PvGQ3kSz4pu",
            "5KqBTaEHatU048ag3ZULf8",
            "5kmHIqA1ob3LDF2D2IKVmu",
            "6IE24khelgX8f9rKZHkBdn",
            "1yA6vwEQ9SNPpz5giz9Gkj",
            "0pKP8JTUFamvSiT5v10YT6",
            "5ImXsScMSy7MKK8G64tgHf",
            "6vBTSKtAv1wbXL0IURUao2",
            "4ksd5ffgM8wkzPTR8hBcNq",
            "5DsFAOgHzLxTWmqRGQqksa",
            "2AWoaZJ8741KegDiILjtwS",
            "6yy54UJRMkbmlvU2RQGz7l",
            "10bd4S3KbsFm3MbCgwP77g",
            "6KJWgH2GfWbXJdYKc8HKGT",
            "09XRQPXPr5jAlF2JbZYWte",
            "3W8wD45K36l58i5Ir8wBd8",
            "5jlKNWgfhNJsurRiKmbRrH",
            "4YXEVWDGMMT7EJbEjvIC7L",
            "3TiCkaJXGgL2Kr6cRgrWKs",
            "7B4MGFxPlw4UwqQdRiQyoG",
            "5uc18oyH3QtNhO5PLjF6Sk",
            "2r8iRbuipPmy2NRX3kgS9E",
            "4uJwnX2JxBSZ07Ey0IDyrO",
            "4a0lfNarYME4cdRx3EyN6z",
            "3gX86OMXW1EyqZvWwQE0eD"
        ]
    },
    {
        "name": "Istasha",
        "spotify": "https://open.spotify.com/artist/5D8TBtxnP5GZm9wUBQ8OTc",
        "instagram": "https://www.instagram.com/istashathescrub/",
        "img": "https://i2o.scdn.co/image/ab676186000016677186c48055380bb80405007e",
        "description": "Istasha (also known as Istasha The Scrub) is an independent artist out of Stockholm, Sweden, operating at the far edges of industrial hip-hop, trap metal, and experimental rap. His music is emotionally raw and sonically restless, blending aggressive production with deeply personal lyrics that sit somewhere between confession and confrontation. He hit the ground running in 2019, dropping a string of projects in rapid succession including Down the Infinite Well, Haute Couture / Red Light District, Djuphavsgraven, and the Scrub Tape, establishing himself quickly as one of the more prolific and unpredictable voices in the underground. After a quieter stretch, he returned strong with Swallowing Centipedes in 2023 and The Distortion That Creates Them in 2024, the latter being some of his most focused and well-received work to date. Entirely independent and self-driven, Istasha has built a cult following across the experimental underground through sheer consistency and a refusal to sand down his edges for anyone.",
        "releases": [
            "6gGlDgErEuvdbkzLYZWBaE",
            "1HzoO0rTvuZFVMxHY3JK27",
            "5O2RH0uuR3GMPz1WkIprNv",
            "5VyaWlfC6avaMJhNeQnKn5",
            "6xIT6dGlBmQTAKhKgAkrRC",
            "4lx3fQXW63THfBWd7sykQ3",
            "1zT0diE4ENHZRJEIefr9yz",
            "2GijnPfiYl2Mbp1Kk8SuFs",
            "2KBcsaj8xhyxDszZNtK39Q",
            "01wJOjiSZCmFZqsPApCdt5",
            "6dSx2hFJLhHDMzadZ1Kee1",
            "7ii8HBQ3nD2nZWHOT7E298",
            "1AculmNlV9qn5OS4L8EoHA",
            "1tAJ9PW4hHDg2WLNY5Ocg6",
            "5k0TNmWJyYy7onlDJbWlOf",
            "2mskJ0qwMugjlMmEeGwHze",
            "4qp9WfLRe8vAqKasE740ep",
            "1r4IymSnKsq4NEIj1Acw9K",
            "6xMpD0WfWC9nJF7hsKoqko",
            "01WEb0iYb9szgzNeANkhQy",
            "6MGgtnMlbFpof4EvM81DPP",
            "3o5imFh5MIPVm10mDTrw26",
            "5qq4P0V5DzQNwcL8yQwpDh",
            "7KsTaHuMCFW5gn1MqNQU0d",
            "086SG7DqKSPcLGYEq1MqcC",
            "66zuGiTfIHFuvrzeh7r4j4",
            "1KjlqinbQ1EQ0boaFOeSE4",
            "0ZUQFYYcpiBbD9DDGYlsTs",
            "0cPB1nqkpcjePZRNKRN27s",
            "5ptACnkDXBGARynwhGeBT2",
            "0KN00znPHdTGbHaM59Vixl",
            "0kdfKGc1dwHeinSNhc7PuI",
            "1yXEkABoNwL1Bo355LelJ8",
            "2ResyJBYR0ZSBN6WlyUeoR",
            "3W7kxkgplRgbOVAHPKBKDd",
            "1rxIEvAI88gl1lBDsjvZqZ",
            "3XaN8KvQmC2Efli52jk692",
            "6hyxT4ayh1Q9xaj8O6JSbs",
            "20CFdpSPETPS6XUqZgkicg",
            "1MsGV5fHGJEh2iSCf9wdTU",
            "1tHCrKGWMtcXhHJrFzbF8F",
            "07XAkk6spuSwW9evI5VpFb",
            "0O23nR5aeadzrHzKkhPbYK",
            "0O1PBPW9r0uN6HYVlzdd4I",
            "38GqeR7ZD5cSRFV782KjsI",
            "6oTp7sLd3wlYsx3AXJJr7Z",
            "68LKkv0YvWBQX34FwfAInf",
            "5FbDnVfo8uezJkMDhoogHc",
            "6aIUqbBn9Nq0k3X2iqozWL",
            "7aDFkcAdT4V8kecsPaZebP",
            "4PNqUm24CbJ8pgs2Ci5ZBh",
            "0cxT3WGzwNWkOB6ozBA9GP",
            "36hoQZ6K7IPxhe2KNP5tF5",
            "78hb9hPjehup1Dd6ICbxod",
            "2G2v4L02C9q3uf9ft76Vn9",
            "0w2pRZ1USaxx0cynb9jyCS",
            "3f2cJJM9eVrmpOUmhftF9x",
            "1leKM5CsRN59M0aG43TXJH",
            "7vLf8zARMbivmonnMWY2qS",
            "0oiwUjuRgICQu4WVGq8sUo",
            "5CnbdmpmoaFoEQZvMHnRyw",
            "4eexWnOtbeQzDVwgn48rvd",
            "13r6C9d42TN49lvcwrv8fI",
            "15P45tgb48FagEukQIC0SZ",
            "1rdW1oyWUDWItFgZ7Vy9yb",
            "1MeD3Gc50YAvSZlao2Nc6E",
            "6XvLoKod7ON7TeDiZlDxKV",
            "2W4RJCtBZKdX0ZdyN06aXT",
            "0UnHhQzAbVVvAGRrUirTMH",
            "6lE9go8qKDK8JR73xCtxlc",
            "4Ie2SY2vMSb05hhs3VU3j2",
            "7E397w3aHqE483jusCkL1f",
            "24FFIn6rtR1p9QAuyDBOJU",
            "3XcHckjLsx8bixliJb9e2o",
            "0UAu1fiVIvlk9PdTHOYPDl",
            "5NpCjajbHRwTnR4vTrmB5k",
            "1yI0QYMukETuhb7MRAgiAC",
            "1h5s6F4l4LypObxNYpKDK0",
            "6jorQmKcGAPcSiCv6PUG15"
        ]
    },
    {
        "name": "Alla Xul Elu",
        "spotify": "https://open.spotify.com/artist/4UbfOzADuGCBOkt2e7CNCV",
        "instagram": "https://www.instagram.com/allaxulelu/",
        "website": "https://longliveevil.bigcartel.com/",
        "img": "https://i2o.scdn.co/image/ab676186000016673371bb7f4dfab63aff08ba93",
        "description": "Alla Xul Elu is a horrorcore trio out of Portsmouth, Ohio, made up of Billy Obey, Joey Black, and Lee Carver, three H.P. Lovecraft and Evil Dead devotees who perform behind grotesque handmade masks and preach a doctrine of wicked humor, dark mythology, and horror-soaked boom bap. They are also the founders of Long Live Evil, one of the most respected independent labels in the underground horror rap scene today. Billy and Joe broke out in 2015 as a duo, dropping Head of Horns and Sci-Co the same year, then added Lee Carver to the lineup and dropped the weed-and-Cthulhu concept EP Necronomichron in 2017. From there things accelerated quickly, with The Almighty (2018), Church of Xul (2019), Mauxuleum (2020), and Gods of Evil Rise (2022) cementing them as one of the premier acts in horrorcore. Now fully independent under Long Live Evil, they dropped Lost Lake Estates in 2023 and their seventh LP No Masters in January 2026. Their sound has evolved over the years, moving between classic horror boom bap, industrial hip-hop, and trap metal, but the identity has never wavered. The Xul Boys answer to no one.",
        "releases": [
            "35Mk9i727TtXV8hxt1EDWg",
            "5B8VDpyIrQrBtt8eyaezUq",
            "0pXXDy8VCpGdyOIYT7OU0r",
            "2VGBOXewJwckHS2scvmWPG",
            "1LJ1sb84K84TBvW9SVX5G8",
            "2VZsxwj7m0bpaHULUkJtOU",
            "4Pc8nnAU0gMuZlLQ3eanpR",
            "287ewtMjm3BrL6we2FyVWf",
            "0BaUzfEXFI5DKMDxP0utli",
            "4SXJUzAIf92r350TYT2nzQ",
            "0RwuFd48IvGM8pyL5RCjEY",
            "4WlGkBCv00rTAX2piNsJ7W",
            "1D137Iz5N3BvXGshKyV5Rk",
            "5QsaGCJtfNNaDNcwvHsPwG",
            "0V3Ep5DUWhlOSIGAxhl533",
            "5Gu41Wd2AuqxsACX4NQTk4",
            "1adlGY8VFdCwoJfKCz5gFE",
            "4B3AiFEnXrpq8NDQGmpfkr",
            "5n9KZORTDCI544umR8nGcY",
            "5LRpvNBXDU7yZyVJ31tasI",
            "6eumzjeuHU83r37yT3V49U",
            "6AuEfrEDWAoD5ohY7ZIKkQ",
            "4LeeV9kXOa09I1PzzDRe9D",
            "77D9TaW9yvbe0qInzzu4I2",
            "51QYHTMgZlbxXGQF8JIcdK",
            "1pRERqhIIRhXee8g6mFsAA",
            "3NRjjsV6W2PqKIXNtVHOha",
            "2H88M1zdCS3JZdlsITgX6y",
            "0FhJ8vHFubhp4IeDgb7VgV",
            "1ZdVkHjNUK4ZeZqcGCyfhs",
            "6QDwdeEygZkEClwhPDzwR4",
            "2eeVnTIsSuXq6NQVLx1SxT"
        ]
    },
    {
        "name": "Neon Sermon",
        "spotify": "https://open.spotify.com/artist/0JgtYVRP5sNDlqoGP62tyX",
        "instagram": "https://www.instagram.com/neonsermon/",
        "website": "https://entershadowland.com/",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/neonsermon.jpg",
        "description": "Neon Sermon is a horrorcore supergroup made up of Philadelphia veteran Lo Key, BatiBatt, and KruX 1, three underground artists who came together with a concept as bold as their sound: an alien collective from the distant planetary system of Cosmosis, arriving on Earth to infiltrate human consciousness through weaponized sound and psychoactive frequencies. They are, according to them, 'definitely NOT plotting world domination.' Central to the group's mythology is Kaos, a mysterious green liquid that symbolizes their power to transform everything it touches. The aesthetic leans hard into neon-drenched, LED-lit sci-fi visuals that look like a rave on a spaceship designed by someone who has fully committed to the bit, blending futuristic alien-hybrid imagery with dark mechanical energy. Musically they hit hard, fusing rapid-fire rap with aggressive electronic music across hardcore rap, EDM, dubstep, and industrial textures, all layered with sci-fi soundscapes and themes bouncing between alien invasion, psychological transformation, party culture, and full-blown cosmic mythology. Their debut 001 dropped in 2022 with 8 tracks of relentless, grimy, high-energy sound that pushes horrorcore into genuinely new sonic territory. One note from the recording sessions that has become something of legend: don't eat the props. The full story remains unclear. Some things are better left a mystery.",
        "releases": [
            "2tRtRaXxmi3xJVKBWVZoBD",
            "3FfQM5bPotguT3Urnw2mMG",
            "0GtG6JMEHzMAaYgeEX9PfV"
        ]
    },
    {
        "name": "BatiBatt",
        "spotify": "https://open.spotify.com/artist/68OJ3J2rE5D1O24GSIZOLd",
        "instagram": "https://www.instagram.com/batibatt_official/",
        "website": "https://entershadowland.com/",
        "img": "https://i2o.scdn.co/image/ab676186000016677a95a3321d0aac98e365a991",
        "description": "BatiBatt is a gothic horror artist out of West Chester, Pennsylvania who has been on a warpath since stepping into the underground scene in 2021. Her signature is a dynamic vocal range that moves fluidly between soft and ethereal to devastating screams, all wrapped in witchy symbolism, occult-themed visuals, and deeply personal themes of self-love, death, revenge, and spiritual awakening. Her debut Virago (2021) came out swinging across eight tracks of trap metal and industrial-influenced aggression, built on psychological turmoil, horror imagery, and demonology. Three years later, Fall From Grace (2024) showed a clear evolution. Still eight tracks, but leaning further into post-metal, melodic singing, and dark pop, expanding her range without softening her edge. The themes of demon lore, human psychology, and introspective self-reflection hit harder for the added dimension, and the artwork, a veiled figure with dark hands covering the face and a crown of thorns dripping blood, is among the most striking in the underground. She followed it up with two singles in 2025, Broken Garden and Wrath, making clear she has no intention of slowing down.",
        "releases": [
            "0tGAwqNwlgYb1AaZQd8hqg",
            "5Uh4tlrunkEKQ04WXue7Ou",
            "5uRIJ1x24ip12DTaXJA4Zt",
            "5jETWden01jtholLQbwyuC",
            "4lgO6ugyt4F0bgwIVfr23v",
            "0jb5FOrMGRT2KxlbFifwFG",
            "2QRr0OYXNscHKjYg3C1dyL",
            "7LVvCjQywCrYaZGtnlsbta",
            "3wHyHoL1WUfSA4rMq4YmkQ",
            "1wF5UP1qjCcGv73bodSNye",
            "3FKqOkVMMoU0mfgcqAjtGX",
            "1D0ydwz68fvtohaH1UT0L4",
            "4G1KuaRb23AtTrHaRC3wgd",
            "3Vcri3GMs1sR73syydSfKO",
            "59JDgfSt13Wl7g5QJ4PJ4L"
        ]
    },
    {
        "name": "Elita",
        "spotify": "https://open.spotify.com/artist/7ApzfFN0BmeeVJPsQBReRv",
        "instagram": "https://www.instagram.com/yungelita/",
        "website": "https://elitamusicworld.com/",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/elita.jpeg",
        "description": "Elita is the project of Emma Harvey, a Canadian singer, songwriter, and actress born and raised in St. John's, Newfoundland. Built alongside her partner Timothy Rypien, the band blends angelic vocals with sinister, bone-chilling lyrics, layering shoegaze, noise, garage rock, and dark pop into a sound that is intimate and unsettling in equal measure. Her themes orbit anxiety, depression, agoraphobia, intrusive thinking, paranoia, and the supernatural, delivered with a vocal quality that feels almost too delicate for the darkness underneath it. She debuted with the single I Hate Everyone but You in 2018 and followed it with the Sick Girl EP in 2019, an honest, raw exploration of different mental states that put her on the map. Her debut album Dysania came next, with cover art shot by legendary fashion photographer Nick Knight. Her most recent release Hell Hill (2025) has been widely praised as her most fully realized work yet, a 45-minute deep dive that finds beauty in abstraction and pushes her experimental sound into new territory while staying rooted in everything that makes Elita distinctly her own.",
        "releases": [
            "7KJtjq7YfLI4kACOIdcHaW",
            "31fM7MbZkDMt1zn51QJ9ap",
            "1W8K5f2dlUlPKOjcPpFse3",
            "1FvAe6SqLX8zG0lD3hGEaU",
            "3DR5jShLK80E3NXJGUKxnp",
            "6nQfaxpSmXxRe9xCOTRBBa",
            "5rxQIohUuObdSEyCeMgLBO",
            "0wi8ZxKcnHoTqBOSypCxRE",
            "1ZihE7uvcauy0odKAIJCY4",
            "3f9hSxQdwLyg5ch1o4xRxt",
            "0Ta0Ro3omKVm0SLTxYX5NP",
            "0jmTbk3JwYNSaMIhAxpef0",
            "41lETiLeuJBY4SmieMV0K7",
            "6AmDiiRIuWbd4y9LqMcvDY",
            "7E6VYflNOZL2cItcb9GRrZ",
            "64RhbtFuXkhlcsRsaZ5uwi",
            "09fwZzRv4EmksZdhUGkvA4",
            "1xIFpGv6PXylrlLYN9bINU",
            "0jvdK0GFKwJYM7WdDICyHi"
        ]
    },
    {
        "name": "Moonvampire",
        "spotify": "https://open.spotify.com/artist/4Fu7HwkDJZ4NFpmefid5TA",
        "instagram": "",
        "img": "https://raw.githubusercontent.com/Moonfire-dreamwalkers/horrorcore-reshare-public-assets/main/images/moonvampire.jpg",
        "description": "Moonvampire is a darkwave and post-punk artist born November 3, 2003, out of Astana, Kazakhstan, building cinematic sonic universes from one of the more unexpected corners of the underground dark music scene. Deep basslines, ethereal synths, haunting vocals, and an atmosphere of melancholy and isolation define the project, drawing comparisons to classic acts in the darkwave and coldwave tradition while maintaining a sound that feels distinctly modern and personal. Since emerging in 2023, Moonvampire has been relentlessly prolific, dropping singles, EPs, and full-lengths at a pace that most artists half his age couldn't sustain. Highlights include the Weird Tales and Weird Tales V.II EPs (2024), the debut LP Bogema (2024), and the albums XXV and Eclipse in 2025, along with a steady stream of singles pushing well into 2026. His favorite of his own tracks is The Sky Full of Bats, which he describes as the most aesthetic song he has made.",
        "releases": [
            "5Hnlxca2tKpaW6Q9lTaZO8",
            "0xUE98VHRPcg4OvFv2EwHM",
            "0MDvWsOneowZlFjWit4mbH",
            "4JcTM0i8Sbrw4H43yN1ngh",
            "4xYRicVDVeB1lMgXEnSpa7",
            "7zjAdyYefDhIkuhhrq0kJN",
            "1c3mnLyeAUsueu9tqJDCIr",
            "5qQ9N0TzIojGvRDLLbkG5s",
            "4NmOvhxJjVWSNouFUiUG9K",
            "1N0nZbiHRbXQ0I1kkAN9fY",
            "3sLGUgkpxUrQh94jYa4OQF",
            "4ecQsecuh6zM7YpoNCklry",
            "5QDm8OKcX6ruB8PngTwz4K",
            "3UtJH7lOow8CtZ0eWDuJBC",
            "0pdxiX7LPU69aXOft2Q3EY",
            "3iNAkpBOGoZ4JligEqydu0"
        ]
    },
    {
        "name": "MOSSBACK",
        "spotify": "https://open.spotify.com/artist/775jQ8mcGabkjuzjt8FShT",
        "instagram": "https://www.instagram.com/33.mossback/",
        "img": "https://i2o.scdn.co/image/ab6761860000166760dda2c2a33543d8e2c95a4c",
        "description": "Mossback is the solo project of Spencer Linn, a singer, songwriter, multi-instrumentalist, and producer from Portland, Oregon with roots stretching back well over a decade across metal, hip-hop, and experimental music. Known widely as one half of Grim Salvo and a member of progressive metal band The Odious, his solo work carves out its own distinct space, leaning into dark hip-hop, introspective lyricism, and atmospheric production built from his own hands. He launched the Mossback name in April 2022 and has steadily grown the project since, with his solo output sitting at a slower, more deliberate pace than his work in Grim Salvo. Songs like Strigoi give a clear sense of the solo direction: haunting, emotionally heavy, and deeply personal, built on imagery of sleeplessness, loss, and psychological unrest. He also runs a Patreon for dedicated supporters looking for a closer look at the creative process. A musician's musician with range across multiple genres and projects, Mossback is one of the more quietly versatile figures in the Portland underground.",
        "releases": [
            "4nX7aNRxdsFWhr3tbTMphD",
            "7BRGKpnbl43wFOxFCFVZfX",
            "5TXaOs14C55MErOkGhtUg7",
            "12JQRQJgtAfW041xzOIFIN",
            "53Yez4WZDLmYk3DBKhAmR9",
            "73fmKfsgfAA3TlzcDJpcQS",
            "49yxCnjxwTEIhrk1VMh5kO",
            "2lD7AjUlZu7n0ZgE5zu6R6",
            "1sY8cQl5Zmgffieid1besU",
            "6eJ9roAVHJTlobJLnvcddw",
            "1tAJ9PW4hHDg2WLNY5Ocg6",
            "0M8oYNUeNSa9M2cVJnKtPv",
            "3l1BSwJgINvLFBUqWveESF",
            "4asDZSQjrUZ8viUTqReQxf",
            "22cPNW8lFbSYNlZRujqf9j",
            "42nVoQFmHrLclAR1cobMzb"
        ]
    },
    {
        "name": "Lo Key",
        "spotify": "https://open.spotify.com/artist/1ehqyqdZUIBIQQP02i8Lmq",
        "instagram": "https://www.instagram.com/lokeylovesyou/",
        "website": "https://shadowlandshop.com/category/lo-key",
        "img": "https://i2o.scdn.co/image/ab6761860000166711038a1cc66783ab6e14384f",
        "description": "Lo Key (Jonathan Thompson) is a Pennsylvania-born emcee, singer-songwriter, and one of the most influential and prolific artists the underground has ever produced. With a career spanning over two decades, he has been cited as a foundational influence by a wide range of artists across the scene and credited as one of the first artists to popularize mask culture in underground hip-hop. What sets Lo Key apart from his peers is an unwillingness to be defined by any single sound. His catalog moves fluidly between horrorcore, heartfelt hip-hop, industrial rock, new metal, electronic, and experimental singer-songwriter territory, often within the same era. While many artists in the scene found a lane and stayed in it, Lo Key has consistently pushed into new territory with each release, making his body of work one of the most varied and unpredictable in the underground. Beyond his solo output, Lo Key has been a central architect of several influential group projects, most notably Mission Infect, a long-running underground super group he founded and helmed across multiple lineups and eras. He has also been a founding member of Neon Sermon, an experimental group blending rap, metal vocals, and electronic production. Lo Key stepped away from live performance in 2018 but has remained one of the most consistently active recording artists in the scene, releasing music through his own platforms including listenlokey.com and Shadowland Shop.",
        "releases": [
            "47GuUjsSYymeK8NLC29834",
            "5im4cZzeuxYHUk3KKhXNWK",
            "7tmcsWICAd1XnxlhJk8Kgm",
            "22NgUDcyZkuGeu4A95dwKz",
            "2W13QJoZ5PlXysGlWQwIKu",
            "7qRcHSSEHjyfycPeLP8ToS",
            "41n0KyuMdmImESXnV5xL8u",
            "1FWsC4RZol50Z2BNaKwgwp",
            "680vUEJmBijs3JjlQVUhit",
            "2GYmZR5WjBULVsGftcNmoY",
            "3HkmnG5veATUWIrkVjaI8m",
            "6Qr8AIKYc1f3jO1VLtNww0",
            "0ak4VkZvF2bm9Iu9eXOsnE",
            "6eRG9Pj4csG4UDizTPZiUK",
            "6jt5yQsBmCbuiLbm2217FU",
            "5Nhl5uwh14VvwZqNToxmcd",
            "0rZ1PXMEP25GPzqUfPOJBO",
            "5FhAJizj7O8BuroDzsbhkn",
            "4NMUzFjPcCL6bNlssYbn5l",
            "05Aos3Pyt0zS2hZ1neqCaO",
            "5jETWden01jtholLQbwyuC",
            "1ds732vdeIMrOTDXWVnwE5",
            "0jb5FOrMGRT2KxlbFifwFG",
            "2QRr0OYXNscHKjYg3C1dyL",
            "7LVvCjQywCrYaZGtnlsbta",
            "3wHyHoL1WUfSA4rMq4YmkQ",
            "1oGAc0AjZxUCaWn8ybyNT0",
            "2djb6nctQpleS2arcmUctN",
            "51QozhAptdwz7DrY8572FY",
            "1cGAIwTY7iipzLGgNthOxJ",
            "6oRR14EYIKjSCrpWlwj3u3",
            "3pTiQkUoNUVLwRaL9TWetH",
            "3Am8KaV1Lab3H4szg1t0QD",
            "6cfK4X81Yh9nmWI8y06NUr",
            "03oClSoVns6EpsK8CW9tG5",
            "7a4ftmG3YUTlQHDHHQWgRo",
            "7vJvsyUD4Sj5eWBM2LWqm1",
            "4lIhWriQ8MjyFphVzj1XcV",
            "0Er1zUj2CXxCH2Wi4LzLSG",
            "0LFHHV1kmVEfrxvVFp8fXa",
            "0MQJFWzIqMffnXg2GxKrpC",
            "2DaQBaPWFcnmaaWZjZAPEg",
            "1GjUeW517s1aXQRFY6MzI3",
            "6s1MIeN70bj2RmVI33BubC",
            "3eoeq5Z3tiCjaOqxxb0Lb2",
            "4fbULd49Ia48nnb1gzfqDt",
            "3BIWgcUPW0D5XDG6mNiw18",
            "26JYI5W9GiWOe61GAMJw9h",
            "3OF32zpSYJG6iErG1QTptA",
            "6IsFCZWzkNjQYn9ISkkLwa",
            "0zHkCx0RHrzcwLW7aFh9fO"
        ]
    }
];
